// ADD NEW LESSONS HERE. Fields separated by "|" . In commands: "^" = new command, "~" = continue on next line.
const S=[["Cloud Basics","☁"],["Compute","🖥"],["Storage","🗄"],["Networking","🌐"],["Databases","🛢"],["Security & IAM","🛡"],["DevOps & Automation","⚙"],["Monitoring & Logging","📈"],["Containers","📦"],["Serverless","λ"],["Data & Analytics","📊"],["AI & ML","🧠"],["Migration & Hybrid","🔄"],["Management & Governance","📋"]];
const LS=[];
const L=(id,t,sub,d,e,s,b,p,f,c,m,tr,k)=>LS.push({id,t,sub,d,e,s,b:b.split("|"),p:p.split("|"),f:f.split("|"),c,m:m.split("|"),tr:tr.split("|"),k:k.split("|")});

L("1.1","Introduction to Cloud Computing","What is cloud computing, why it matters, and how AWS helps businesses.",
"Cloud computing provides on-demand access to computing resources like servers, storage, databases, networking, analytics, and more over the internet.",
"Instead of buying and maintaining physical servers, you use AWS resources on demand, pay only for what you use, and scale anytime.",
"A growing e-commerce company gets high traffic during sales (e.g., Big Billion Days). They use AWS to quickly scale servers, handle millions of users, and reduce resources after the sale.",
"No physical hardware|Pay as you go|High availability|Global reach|Scalability|Focus on business, not infrastructure",
"Login to AWS Console|Go to EC2 service|Launch an EC2 instance|Choose Amazon Linux 2|Select instance type (t2.micro)|Configure security group (allow SSH)|Launch and connect using SSH",
"🔑 Console Login|🔲 EC2|🚀 Launch|💻 Connect",
"aws ec2 run-instances~--image-id ami-0abcdef1234567890~--instance-type t2.micro~--key-name my-key~--security-group-ids sg-12345678",
"Leaving resources running (unexpected charges)|Incorrect security group rules|Choosing wrong region|Not monitoring usage",
"S – Scale|P – Pay only for use|F – Focus on business",
"Cloud = Internet + On-demand Resources|AWS provides global infrastructure|Pay as you go|Use Console / CLI / SDK|Key services: EC2, S3, RDS, VPC, IAM");

L("1.2","Cloud Service Models","IaaS, PaaS and SaaS: who manages what.",
"Service models decide how much you manage. IaaS gives raw servers and networks, PaaS gives a ready platform to run code, SaaS gives a finished app.",
"IaaS = rent an empty kitchen. PaaS = rent a kitchen with tools, you only cook. SaaS = order food that is already made.",
"A startup runs its website on EC2 (IaaS), deploys its API on Elastic Beanstalk (PaaS), and uses Gmail and Slack (SaaS) for email and chat.",
"Choose the control level you need|Less admin work with PaaS and SaaS|Faster launch|Pay only for the layer you use",
"Open the EC2 console (IaaS example)|Open Elastic Beanstalk (PaaS example)|Compare what you must manage in each|Note that SaaS needs only a login",
"🧱 IaaS|🛠 PaaS|📱 SaaS",
"aws ec2 describe-instances^aws elasticbeanstalk describe-applications",
"Using IaaS when PaaS is enough|Forgetting you still patch the OS in IaaS|Confusing PaaS with SaaS",
"I = Infrastructure (you do most)|P = Platform (you bring code)|S = Software (you just use)",
"IaaS: EC2, VPC|PaaS: Elastic Beanstalk, RDS|SaaS: WorkMail, Chime|More control = more work");

L("1.3","Cloud Deployment Models","Public, private and hybrid cloud.",
"Deployment models describe where your resources live: public cloud (AWS), private cloud (your own data centre), or hybrid (both connected).",
"Public = rent a flat. Private = own house. Hybrid = own house plus a rented flat for extra guests.",
"A bank keeps customer records in its own data centre but runs its mobile app and analytics on AWS, connected by a private link.",
"Flexibility to choose where data lives|Helps meet rules for sensitive data|Burst to cloud when busy|Move to cloud step by step",
"Open the VPC console|Find Site-to-Site VPN connections|See where Direct Connect is listed|Read how on-premises connects to a VPC",
"🏢 On-premises|🔗 VPN / Direct Connect|☁ AWS VPC",
"aws configure list^aws ec2 describe-vpn-connections",
"Going hybrid without a clear reason|Ignoring network delay between sites|Skipping security on the link",
"Public = Rent|Private = Own|Hybrid = Both",
"Public: AWS|Private: your data centre or Outposts|Hybrid: VPN or Direct Connect|Pick by cost, rules and speed");

L("1.4","Global Infrastructure","Regions, Availability Zones and Edge Locations.",
"AWS is split into Regions (geographic areas), each with multiple Availability Zones (separate data centres). Edge locations cache content close to users.",
"Region = a city. AZ = separate buildings in that city. Edge location = a small local shop that stores popular items.",
"An Indian streaming app runs in Mumbai (ap-south-1) across 3 AZs and uses CloudFront edge locations so videos load fast everywhere.",
"Low delay for users|Survives a data centre failure|Meets data location rules|Easy to expand worldwide",
"Open the region dropdown in the console|Select Asia Pacific (Mumbai)|Open EC2 and view Availability Zones|Launch resources in two different AZs",
"🌍 Region|🏢 Availability Zone|📡 Edge Location",
"aws ec2 describe-regions --output table^aws ec2 describe-availability-zones --region ap-south-1",
"Choosing a far region (high delay)|Keeping everything in one AZ|Forgetting services differ by region",
"R = Region (area)|A = AZ (data centres)|E = Edge (cache)",
"A Region has 2 or more AZs (usually 3)|AZs are linked by fast networks|Edge locations power CloudFront|Mumbai = ap-south-1");

L("1.5","Shared Responsibility","Who secures what: AWS or you.",
"AWS secures the cloud itself (hardware, buildings, network). You secure what you put in the cloud (data, access, settings, OS patches on EC2).",
"AWS builds a strong building with locks. You decide who gets keys and what you keep inside.",
"A company stores customer files in S3. AWS protects the data centre. The company must keep the bucket private and use IAM rules.",
"Clear security ownership|Less hardware worry|Focus on data and access|Easier audits",
"Open the IAM console|Check users and their permissions|Open S3 and check Block Public Access|Review EC2 security groups",
"☁ AWS: security OF the cloud|👤 You: security IN the cloud",
"aws iam get-account-summary^aws s3api get-public-access-block --bucket my-bucket",
"Thinking AWS secures your data automatically|Public S3 buckets|Never patching EC2 instances",
"OF = AWS|IN = You",
"AWS: hardware, facilities, network|You: data, IAM, firewall rules|EC2 OS patching is yours|RDS patching is mostly AWS");

L("1.6","Benefits of Cloud","Why companies move to the cloud.",
"Cloud benefits: lower upfront cost, fast scaling, high availability, global reach, and faster experiments.",
"No big purchase. Rent what you need today, give it back tomorrow.",
"A school result website gets 100x traffic for one day. On AWS it scales up that day and costs very little the rest of the year.",
"Lower upfront cost|Scale up and down|Better uptime|Launch in minutes",
"Open the Billing console|View Free Tier usage|Set a budget alert (e.g. 5 USD)|Check Cost Explorer",
"💰 Low cost|📈 Scale|🌍 Global|⚡ Fast",
"aws budgets describe-budgets --account-id 123456789012",
"Not setting budget alerts|Leaving test resources running|Assuming cloud is always cheaper",
"C – Cost saving|A – Agility|G – Global reach",
"Big upfront spend becomes monthly spend|Elasticity = grow and shrink|Free Tier helps learning|Always set budgets");

L("5.1","Amazon RDS","Managed relational databases.",
"Amazon RDS runs managed relational databases (MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, Aurora). AWS handles backups, patching and failover.",
"A database where AWS does the boring admin work, so you focus on tables and queries.",
"An online store runs PostgreSQL on RDS with Multi-AZ so orders keep working even if one data centre fails.",
"Automatic backups|Multi-AZ failover|Read replicas for speed|Easy patching",
"RDS > Create database|Pick MySQL or PostgreSQL|Choose the Free tier template|Set username and password|Allow the DB port only from your app's security group",
"💻 App|🛢 RDS|🔁 Standby / Replica",
"aws rds create-db-instance~--db-instance-identifier mydb~--engine postgres~--db-instance-class db.t3.micro~--allocated-storage 20~--master-username admin --master-user-password <password>",
"Making the database public|Weak master password|Low backup retention|Leaving it running when idle",
"RDS = SQL tables|Multi-AZ = Safety|Read replica = Speed",
"Relational (SQL) engines|Multi-AZ for high availability|Read replicas for scale|Aurora is AWS's own engine");

L("5.2","Amazon DynamoDB","Serverless NoSQL database.",
"DynamoDB is a serverless NoSQL key-value and document database with single-digit millisecond speed at any scale.",
"A super-fast digital notebook where you look things up by a key, and it never runs out of pages.",
"A game app stores player scores in DynamoDB and reads them in milliseconds for millions of players.",
"No servers to manage|Very fast at any scale|Pay per request option|Global tables",
"DynamoDB > Create table|Set a partition key (e.g. userId)|Choose On-demand capacity|Add items with Create item|Query by key",
"🔑 Key|📄 Item|🗂 Table",
"aws dynamodb create-table~--table-name Players~--attribute-definitions AttributeName=userId,AttributeType=S~--key-schema AttributeName=userId,KeyType=HASH~--billing-mode PAY_PER_REQUEST",
"Choosing a bad partition key|Using Scan on big tables|Treating it like SQL with joins|Over-provisioning capacity",
"Key = Find fast|No joins|Design by access pattern",
"NoSQL key-value|Partition key + optional sort key|On-demand or provisioned|Use Query, not Scan");

L("6.1","AWS IAM","Who can do what in your account.",
"IAM controls who can do what in your AWS account using users, groups, roles and policies.",
"The security desk of your account: it checks who you are and what you are allowed to touch.",
"A team gives developers read-only S3 access and gives an EC2 server a role to write logs, with no hard-coded keys.",
"Fine-grained permissions|No shared passwords|Roles for services|Free to use",
"IAM > Users > Create user|Add the user to a group with a policy|Enable MFA|Create a role for EC2 with S3 read access|Do not use root for daily work",
"👤 User|👥 Group|📜 Policy|🎭 Role",
"aws iam create-user --user-name dev1^aws iam attach-user-policy --user-name dev1 --policy-arn arn:aws:iam::aws:policy/ReadOnlyAccess",
"Using the root account|Giving AdministratorAccess to everyone|Hard-coding access keys in code|No MFA",
"Least privilege = Only what is needed|Roles over keys",
"User = person|Role = temporary identity|Policy = JSON permissions|Always enable MFA");

L("8.1","Amazon CloudWatch","Metrics, logs and alarms.",
"CloudWatch collects metrics, logs and alarms from AWS services and your apps so you can watch health and react.",
"A dashboard and alarm system for your servers. It tells you when CPU is high or something breaks.",
"A company gets an email alert when the CPU of its web servers stays above 80% for 5 minutes.",
"One place for metrics and logs|Alarms with notifications|Dashboards|Can trigger Auto Scaling",
"CloudWatch > Alarms > Create alarm|Select the EC2 CPUUtilization metric|Set threshold 80%|Send to an SNS email topic|Confirm the email subscription",
"📊 Metric|🔔 Alarm|📧 SNS|⚙ Action",
"aws cloudwatch describe-alarms^aws logs tail /aws/lambda/my-fn --follow",
"No alarms at all|Logs kept forever (cost)|Alerting on too many things|Forgetting the SNS confirmation",
"Metric = Number|Log = Text|Alarm = Alert",
"Basic metrics every 5 min|Logs live in log groups|Alarm states: OK, ALARM|Pair with SNS");

L("10.1","AWS Lambda","Run code without servers.",
"AWS Lambda runs your code without servers. You upload a function, AWS runs it on events, and you pay only for run time.",
"Write a small function and AWS runs it when something happens. No server to manage.",
"When a photo is uploaded to S3, a Lambda function creates a thumbnail automatically.",
"No server management|Pay per request and time|Scales automatically|Many triggers",
"Lambda > Create function|Choose Python, Author from scratch|Paste your code|Add a trigger (S3 or API Gateway)|Click Test",
"⚡ Event|λ Lambda|📤 Result",
"aws lambda invoke --function-name my-fn out.json^aws lambda list-functions",
"Timeout too short|Too little memory|Huge packages|Missing IAM role permissions",
"Event in > Code runs > Pay little",
"Max run time 15 minutes|Memory 128 MB to 10 GB|Triggers: S3, API Gateway, SQS|Billed per millisecond");

// ===== COMPUTE =====
L("2.1","EC2 Basics","Virtual servers in the cloud.",
"Amazon EC2 gives resizable virtual servers called instances. You choose OS, CPU, memory, storage and network, and pay per second or hour.",
"A computer you rent by the hour. Stop it and compute billing stops.",
"A web shop runs its site on EC2, adds more instances before a sale, then stops them after.",
"Many instance types|Full OS control|Pay only for use|Scales with Auto Scaling",
"Console > EC2 > Launch instance|Name it and pick the Amazon Linux AMI|Choose a Free Tier type (t2.micro or t3.micro)|Create a key pair and allow SSH in the security group|Launch and connect with SSH",
"🔑 Login|🔲 EC2|🚀 Launch|💻 Connect",
"aws ec2 start-instances --instance-ids i-0abc123^aws ec2 stop-instances --instance-ids i-0abc123^aws ec2 terminate-instances --instance-ids i-0abc123",
"Leaving instances running|Opening SSH to 0.0.0.0/0|Losing the key pair|Confusing Stop with Terminate",
"Stop = Pause|Terminate = Delete forever|Always check the bill",
"Instance states: pending, running, stopped, terminated|Public IP changes on stop/start (use Elastic IP)|Stopped = no compute charge, EBS still billed|Region and AZ are chosen at launch");

L("2.2","Instance Types & Pricing","Pick the right size and the cheapest way to pay.",
"Instance types are grouped by purpose: General (t, m), Compute (c), Memory (r), Storage (i, d), GPU (p, g). Pricing models: On-Demand, Savings Plans or Reserved, Spot, Dedicated Host.",
"Like renting vehicles: a scooter for small jobs, a truck for heavy loads. Pay daily (On-Demand), take a yearly deal (Savings Plan), or grab a cheap leftover seat that can be taken back (Spot).",
"A company runs steady database servers on 1-year Savings Plans, web servers On-Demand, and nightly video jobs on Spot to save up to about 90%.",
"Right-size for the job|Save with Savings Plans|Spot for cheap flexible jobs|Dedicated Hosts for licence rules",
"Open EC2 > Instance Types|Filter by vCPU and memory|Compare t3.micro and m5.large|Open the AWS Pricing Calculator|Pick a pricing model for your workload",
"🧮 Estimate|📦 Pick type|💲 Pick pricing|📉 Monitor",
"aws ec2 describe-instance-types --instance-types t3.micro^aws ec2 describe-spot-price-history --instance-types t3.micro --product-descriptions Linux/UNIX",
"Choosing a size too big|Using Spot for critical servers|No Savings Plan for steady load|Ignoring burst credits on t-types",
"T = Tiny / burst|M = Middle / balanced|C = CPU|R = RAM",
"t, m = general|c = compute heavy|r = memory heavy|Spot can be stopped with 2 minutes notice");

L("2.3","AMI, Key Pairs & User Data","Templates, login keys and boot scripts.",
"An AMI is a template with the OS and software for new instances. A key pair gives secure SSH login. User data is a script that runs when the instance first starts.",
"AMI = a ready photocopy of a computer. Key pair = the key to open it. User data = a to-do note it follows on first boot.",
"A team builds a custom AMI with their app installed, so every new server in Auto Scaling starts identical and ready.",
"Identical servers every time|Faster launches|Safe passwordless login|Automatic setup with scripts",
"EC2 > Launch instance and pick an AMI|Create a key pair and download the .pem file|Open Advanced details > User data|Paste a script that installs nginx|Launch and open the public IP in a browser",
"📀 AMI|🔑 Key Pair|📜 User Data|🔲 Instance",
"aws ec2 create-key-pair --key-name my-key --query KeyMaterial --output text > my-key.pem^chmod 400 my-key.pem^ssh -i my-key.pem ec2-user@<public-ip>^aws ec2 create-image --instance-id i-0abc123 --name my-app-ami",
"Losing the .pem file (cannot download again)|Wrong file permissions on .pem|Putting secrets in user data|Forgetting AMIs are regional",
"AMI = Template|Key = Login|User data = Boot script",
"chmod 400 key.pem|User data runs once at first boot|AMI is region specific|Default user: ec2-user (Amazon Linux)");

L("2.4","EC2 Security Groups","The instance-level firewall.",
"A security group is a virtual firewall attached to an instance. It allows only the traffic you permit, with separate inbound and outbound rules.",
"A guard at the door with a guest list. If you are not on the list, you do not enter.",
"A web server's group allows ports 80 and 443 from anywhere, and SSH (22) only from the office IP.",
"Instance-level protection|Stateful (replies allowed automatically)|Allow rules only|Can reference other groups",
"EC2 > Security Groups > Create|Add inbound HTTP 80 from anywhere|Add SSH 22 from My IP|Attach it to the instance|Test access in a browser",
"🌐 Internet|🛡 Security Group|🔲 Instance",
"aws ec2 create-security-group --group-name web-sg --description web --vpc-id vpc-0abc123^aws ec2 authorize-security-group-ingress --group-id sg-0abc123 --protocol tcp --port 80 --cidr 0.0.0.0/0",
"SSH open to 0.0.0.0/0|Too many ports open|Deleting outbound rules by mistake|Expecting deny rules (not supported)",
"SG = Allow list only|Stateful = Replies are free",
"Allow rules only, no deny|Default: inbound blocked, outbound allowed|Stateful|Many groups per instance allowed");

L("2.5","Auto Scaling","Add and remove servers automatically.",
"An Auto Scaling Group (ASG) keeps the right number of EC2 instances. It uses a launch template, min / desired / max sizes, health checks and scaling policies.",
"More customers, open more counters. Fewer customers, close some. If a counter breaks, it is replaced.",
"A ticket site doubles its servers when sales open and drops back at night, paying only for what ran.",
"Handles traffic spikes|Saves cost|Replaces unhealthy servers|Works across AZs",
"Create a Launch Template (AMI, type, security group)|Create an Auto Scaling Group|Select 2 or more subnets in different AZs|Set Min 1, Desired 2, Max 4|Add a Target tracking policy at 50% CPU",
"📈 Metric|⚙ Policy|➕ Scale out|➖ Scale in",
"aws autoscaling create-auto-scaling-group~--auto-scaling-group-name web-asg~--launch-template LaunchTemplateName=web-lt~--min-size 1 --max-size 4~--vpc-zone-identifier subnet-111,subnet-222",
"Min and max set wrong|Only one AZ|No health checks|Very long cooldown wastes money",
"Min = Floor|Max = Ceiling|Desired = Right now",
"Scale out = add, scale in = remove|Target tracking is the simplest policy|Scheduled scaling for known peaks|Health check: EC2 or ELB");

L("2.6","Elastic Load Balancer","Share traffic across servers.",
"ELB spreads incoming traffic across many targets in multiple AZs. Types: Application (HTTP/HTTPS), Network (TCP/UDP, very fast), Gateway (security appliances).",
"A manager at the door who sends each customer to a free counter and skips closed ones.",
"An app uses an ALB: /api goes to API servers and /images goes to image servers, all behind one URL.",
"Single entry point|Health checks remove bad servers|HTTPS with ACM certificates|Path and host routing",
"EC2 > Load Balancers > Create Application Load Balancer|Pick 2 public subnets|Create a target group on port 80|Register instances or the Auto Scaling Group|Open the ALB DNS name",
"👥 Users|⚖ ALB|🎯 Target Group|🔲 EC2",
"aws elbv2 create-load-balancer --name web-alb --subnets subnet-111 subnet-222 --security-groups sg-0abc123^aws elbv2 create-target-group --name web-tg --protocol HTTP --port 80 --vpc-id vpc-0abc123",
"Wrong health check path|Instance SG not allowing the ALB|Only one AZ|Leaving the ALB running (hourly cost)",
"ALB = Apps (HTTP)|NLB = Network (TCP, fast)|GWLB = Gateway",
"ALB: path and host rules|NLB: static IP, very high speed|Target group = list of backends|Use ACM for HTTPS");

// ===== STORAGE: S3 =====
L("3.1","S3 Basics","Object storage for any file.",
"Amazon S3 is object storage. You store files (objects) in buckets and get very high durability (99.999999999%).",
"A huge online locker where each file has its own link and you pay only for the space used.",
"A news site keeps all images and videos in S3 and serves them through CloudFront.",
"Practically unlimited storage|11 nines durability|Cheap storage classes|Works with almost every AWS service",
"Console > S3 > Create bucket|Pick a unique name and region|Keep Block Public Access ON|Upload a file|Open it with a presigned URL",
"📁 Bucket|📄 Object|🔐 Permissions",
"aws s3 mb s3://my-unique-bucket-123^aws s3 cp notes.txt s3://my-unique-bucket-123/^aws s3 ls s3://my-unique-bucket-123",
"Bucket name already taken|Making buckets public by mistake|Using S3 like a disk for databases|No cost monitoring",
"Bucket = Box|Object = File (key + data)|Never public by default",
"Object storage, not block|Bucket names are globally unique|Max object size 5 TB|Data stays in the chosen region");

L("3.2","S3 Storage Classes","Pay less for data you rarely use.",
"Storage classes trade price for access speed: Standard, Intelligent-Tiering, Standard-IA, One Zone-IA, Glacier Instant, Glacier Flexible, Glacier Deep Archive.",
"Fridge (Standard), store room (IA), locked cellar (Glacier). Cheaper places take longer to fetch from.",
"A hospital keeps recent scans in Standard and moves old ones to Glacier Deep Archive for cheap long-term storage.",
"Big savings on old data|Automatic tiering available|Same 11 nines durability|Pick by access pattern",
"Upload a file in S3|Open Properties and find Storage class|Choose Standard-IA|Compare with Glacier options|Check the per-GB price",
"🔥 Hot|🌤 Warm|❄ Cold|🧊 Archive",
"aws s3 cp file.zip s3://my-unique-bucket-123/ --storage-class STANDARD_IA^aws s3api list-objects-v2 --bucket my-unique-bucket-123",
"IA for tiny files (minimum size charge)|Early delete fees|Standard for everything|Forgetting retrieval time and cost",
"Frequent = Standard|Rare = IA|Archive = Glacier",
"Standard: frequent access|Standard-IA: 30 day minimum|Glacier: minutes to hours|Intelligent-Tiering: auto moves data");

L("3.3","S3 Versioning & Lifecycle","Undo mistakes and clean up automatically.",
"Versioning keeps every version of an object, so deletes and overwrites can be undone. Lifecycle rules move or delete objects automatically after set days.",
"Versioning = undo button. Lifecycle = a clean-up robot that moves old files to cheaper shelves and throws very old ones away.",
"A company turns on versioning for reports and moves versions older than 30 days to Glacier, deleting them after 1 year.",
"Recover from mistakes|Protect against overwrites|Automatic cost saving|Helps compliance",
"Open bucket > Properties|Enable Bucket Versioning|Upload the same file twice|Show versions and restore the old one|Management > Create lifecycle rule",
"📄 v1|📄 v2|🗑 Delete marker|⏳ Lifecycle",
"aws s3api put-bucket-versioning --bucket my-unique-bucket-123 --versioning-configuration Status=Enabled^aws s3api list-object-versions --bucket my-unique-bucket-123",
"Old versions pile up (cost)|No lifecycle for old versions|Thinking delete removes the data|Cannot fully disable versioning (only suspend)",
"Versioning = Undo|Lifecycle = Auto move / delete",
"Delete adds a delete marker|You can only suspend versioning|Lifecycle: transition and expiration|MFA Delete adds protection");

L("3.4","S3 Security & Access","Policies, public access and encryption.",
"S3 access is controlled by IAM policies, bucket policies, ACLs and Block Public Access. Data can be encrypted at rest (SSE-S3, SSE-KMS) and in transit (HTTPS).",
"Bucket = locker. IAM and bucket policy decide who gets keys. Block Public Access is the master lock. Encryption is a safe inside the locker.",
"A fintech keeps all buckets private, uses IAM roles for apps, and encrypts with KMS keys to pass audits.",
"Private by default|Fine-grained access|Built-in encryption|Access logs for audits",
"Keep Block Public Access ON|Open Permissions > Bucket policy|Add a policy for one IAM role|Set default encryption (SSE-S3 or SSE-KMS)|Create a presigned URL to share a file",
"👤 Principal|📜 Policy|🔐 Encryption|📋 Logs",
"aws s3api put-public-access-block --bucket my-unique-bucket-123 --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true^aws s3 presign s3://my-unique-bucket-123/notes.txt --expires-in 3600",
"Public buckets|Using ACLs instead of policies|No encryption|Sharing long-term access keys",
"Block first|Policy next|Encrypt always",
"Block Public Access = master switch|Encryption options: SSE-S3, SSE-KMS, SSE-C|New objects are encrypted by default|Presigned URL = temporary link");

L("3.5","S3 Static Website Hosting","Host a website with no server.",
"S3 can host static websites (HTML, CSS, JS, images). You enable website hosting, set index and error documents, and allow public read.",
"Put your website files in a locker that opens to the public. No server needed.",
"A portfolio site lives in S3 with CloudFront in front and costs very little per month.",
"No servers to manage|Very cheap|Highly available|Pairs with CloudFront and Route 53",
"Create a bucket and upload index.html|Properties > Static website hosting > Enable|Set the index document to index.html|Turn off Block Public Access for this bucket only|Add a public-read bucket policy and open the website URL",
"📁 Bucket|🌐 Website endpoint|👥 Visitors",
"aws s3 sync ./site s3://my-site-bucket^aws s3 website s3://my-site-bucket --index-document index.html --error-document error.html",
"Forgetting the bucket policy (403 error)|Expecting HTTPS on the website endpoint|Trying to host dynamic apps|Mixing private data in the same bucket",
"Static only|Public read|CloudFront for HTTPS",
"Only static content|Website endpoint is HTTP only|403 = missing public policy|Use CloudFront for HTTPS");

// ===== STORAGE: EBS =====
L("3.6","EBS Volumes & Types","Disks for your EC2 servers.",
"EBS gives block storage volumes that attach to an EC2 instance in the same AZ. Types: gp3 and gp2 (general SSD), io2 and io1 (high IOPS SSD), st1 (throughput HDD), sc1 (cold HDD).",
"A pen drive plugged into your rented computer. It keeps data even if the computer stops.",
"A normal database uses a gp3 volume. A critical banking database uses io2 for guaranteed IOPS.",
"Persistent disk|Resize while running|Encryption built in|Choose speed vs cost",
"EC2 > Volumes > Create volume|Choose gp3, 8 GiB, same AZ as the instance|Attach it to the instance|Run lsblk, then format and mount it|Check Delete on termination",
"💽 Volume|🔌 Attach|🔲 EC2|📂 Mount",
"aws ec2 create-volume --size 8 --volume-type gp3 --availability-zone ap-south-1a^aws ec2 attach-volume --volume-id vol-0abc123 --instance-id i-0abc123 --device /dev/sdf",
"Different AZ than the instance|Unused volumes still billed|Not mounting after attaching|HDD types for databases",
"gp = General|io = Fast IOPS|st = Throughput|sc = Cold",
"Same AZ only|gp3 is the default and cheapest SSD|Root volume deletes on termination by default|Can grow, cannot shrink");

L("3.7","EBS Snapshots","Backups for your volumes.",
"A snapshot is a point-in-time backup of an EBS volume, stored in S3 by AWS. The first is full, later ones are incremental.",
"Take a photo of your disk. Later photos only save what changed.",
"A team takes nightly snapshots with Data Lifecycle Manager and restores a volume after a bad update.",
"Cheap incremental backups|Restore in any AZ|Copy to other regions|Create AMIs from them",
"EC2 > Volumes > select a volume|Actions > Create snapshot|Open Snapshots to see it|Create a volume from the snapshot in another AZ|Set a Data Lifecycle Manager policy",
"💽 Volume|📸 Snapshot|♻ Restore|🌍 Copy",
"aws ec2 create-snapshot --volume-id vol-0abc123 --description nightly^aws ec2 copy-snapshot --source-region ap-south-1 --source-snapshot-id snap-0abc123 --region ap-southeast-1",
"No backup schedule|Deleting snapshots an AMI needs|Not testing restores|Forgetting old snapshots (cost)",
"Snapshot = Photo|Incremental = Only changes",
"Incremental after the first|Stored regionally|Can move between AZs and Regions|Automate with DLM");

// ===== NETWORKING: VPC =====
L("4.1","VPC Basics","Your private network in AWS.",
"A VPC is your private network in AWS. You control IP ranges, subnets, route tables, gateways and firewalls.",
"Your own fenced plot inside AWS. You decide the gates, roads and who can enter.",
"A company puts its web servers in a public subnet and its database in a private subnet with no direct internet access.",
"Network isolation|Full control of IP ranges|Public and private subnets|Layered security",
"VPC > Create VPC (VPC and more)|Use CIDR 10.0.0.0/16|Create public and private subnets|Attach an Internet Gateway|Add a route to it in the public route table",
"🌐 Internet|🚪 Internet Gateway|🧭 Route Table|🧩 Subnet",
"aws ec2 create-vpc --cidr-block 10.0.0.0/16^aws ec2 create-subnet --vpc-id vpc-0abc123 --cidr-block 10.0.1.0/24",
"Overlapping CIDR ranges|Databases in public subnets|Missing route to the internet gateway|Mixing up Security Group and NACL",
"VPC = Your network|Subnet = A part of it|Gateway = The door",
"A VPC is regional, a subnet is per AZ|Every account gets a default VPC|CIDR range /16 to /28|Plan IP ranges before you build");

L("4.2","Subnets & Route Tables","Split the network and control traffic paths.",
"A subnet is a slice of the VPC IP range in one AZ. A route table decides where subnet traffic goes. A subnet is public if its route table sends 0.0.0.0/0 to an Internet Gateway.",
"Subnet = a street in your colony. Route table = signboards telling traffic which road to take.",
"Web servers sit in public subnets in 2 AZs, and databases sit in private subnets with routes only inside the VPC.",
"Separate public and private areas|Spread across AZs|Control traffic paths|Better security",
"VPC > Subnets > Create subnet (10.0.1.0/24, AZ a)|Create another in AZ b|Create a route table|Add route 0.0.0.0/0 to the Internet Gateway|Associate it with the public subnets",
"🧩 Subnet|🧭 Route Table|🚪 Gateway",
"aws ec2 create-route-table --vpc-id vpc-0abc123^aws ec2 create-route --route-table-id rtb-0abc123 --destination-cidr-block 0.0.0.0/0 --gateway-id igw-0abc123",
"Subnet left on the main route table|CIDR range too small|All subnets in one AZ|Forgetting to associate the route table",
"Public = Route to IGW|Private = No IGW route",
"A subnet lives in one AZ|AWS reserves 5 IPs per subnet|Local route is automatic|One route table per subnet");

L("4.3","Internet Gateway & NAT","Internet access, safely.",
"An Internet Gateway (IGW) connects a VPC to the internet. A NAT Gateway lets private servers reach the internet outward only, without being reachable from outside.",
"IGW = main gate of your colony. NAT = a courier who goes out for you and brings the answer back, but strangers cannot walk in.",
"Private app servers download updates through a NAT Gateway placed in a public subnet.",
"Safe outbound access|Servers stay hidden|IGW is free|NAT scales automatically",
"Create and attach an Internet Gateway|Create a NAT Gateway in a public subnet with an Elastic IP|Edit the private route table|Add 0.0.0.0/0 pointing to the NAT Gateway|Test curl from a private instance",
"🔒 Private EC2|🔁 NAT|🚪 IGW|🌐 Internet",
"aws ec2 create-internet-gateway^aws ec2 create-nat-gateway --subnet-id subnet-111 --allocation-id eipalloc-0abc123",
"NAT placed in a private subnet|NAT left running (hourly + data cost)|No Elastic IP|One NAT for all AZs (single point of failure)",
"IGW = In and out|NAT = Out only",
"NAT lives in a public subnet|Costs per hour plus per GB|IPv6 uses Egress-only IGW|One IGW per VPC");

L("4.4","Security Group vs NACL","Two firewalls, two levels.",
"Security groups work at the instance level and are stateful. Network ACLs work at the subnet level, are stateless, and support allow and deny rules checked in number order.",
"SG = guard at your flat door. NACL = guard at the colony gate who checks both entry and exit.",
"A company blocks one bad IP range with a NACL deny rule while security groups handle normal access per server.",
"Two layers of defence|NACL can deny|SG is easy per app|Defence in depth",
"Open VPC > Network ACLs|View the default inbound and outbound rules|Add a deny rule for a test IP range|Compare with a Security Group|Test with a connection",
"🏘 NACL (subnet)|🛡 SG (instance)|🔲 EC2",
"aws ec2 create-network-acl --vpc-id vpc-0abc123^aws ec2 create-network-acl-entry --network-acl-id acl-0abc123 --rule-number 100 --protocol tcp --port-range From=22,To=22 --cidr-block 203.0.113.0/24 --rule-action deny --ingress",
"Forgetting return (ephemeral) ports in NACL|Wrong rule order|Using NACL for everything|Expecting SG to deny",
"SG = Stateful, Allow only|NACL = Stateless, Allow + Deny",
"SG: instance level, stateful|NACL: subnet level, stateless|NACL rules checked by number|Default NACL allows all");

L("4.5","VPC Peering & Endpoints","Private links to other VPCs and AWS services.",
"VPC Peering privately connects two VPCs. VPC Endpoints let your VPC reach AWS services (like S3) privately without the internet.",
"Peering = a private road between two colonies. Endpoint = a private door straight to AWS services.",
"Two teams connect their VPCs with peering, and private servers reach S3 through a gateway endpoint without NAT cost.",
"Private traffic|Lower NAT cost|Better security|Simple setup",
"VPC > Peering connections > Create|Accept the request in the other VPC|Add routes in both route tables|Create a Gateway endpoint for S3|Update the private route table",
"🏘 VPC A|🔗 Peering|🏘 VPC B",
"aws ec2 create-vpc-peering-connection --vpc-id vpc-0aaa --peer-vpc-id vpc-0bbb^aws ec2 create-vpc-endpoint --vpc-id vpc-0abc123 --service-name com.amazonaws.ap-south-1.s3 --route-table-ids rtb-0abc123",
"Overlapping CIDRs (peering fails)|Missing routes on both sides|Expecting transitive peering|Not accepting the request",
"Peering = VPC to VPC|Endpoint = VPC to AWS service",
"No overlapping CIDR|Peering is not transitive|Gateway endpoints: S3 and DynamoDB (free)|Interface endpoint uses PrivateLink");

LS.sort((a,b)=>{const x=a.id.split(".").map(Number),y=b.id.split(".").map(Number);return x[0]-y[0]||x[1]-y[1]});
