// ADD NEW LESSONS HERE. Fields separated by "|" . In commands: "^" = new command, "~" = continue on next line.
const S=[["Cloud Basics","☁"],["Compute","🖥"],["Storage","🗄"],["Networking","🌐"],["Databases","🛢"],["Security & IAM","🛡"],["DevOps & Automation","⚙"],["Monitoring & Logging","📈"],["Containers","📦"],["Serverless","λ"],["Data & Analytics","📊"],["AI & ML","🧠"],["Migration & Hybrid","🔄"],["Management & Governance","📋"]];
const LS=[];
const L=(id,t,sub,d,e,s,b,p,f,c,m,tr,k)=>LS.push({id,t,sub,d,e,s,b:b.split("|"),p:p.split("|"),f:f.split("|"),c,m:m.split("|"),tr:tr.split("|"),k:k.split("|")});

L("1.1","Introduction to Cloud Computing","What is cloud computing, why it matters, and how AWS helps businesses.",
"Cloud computing provides on-demand access to computing resources like servers, storage, databases, networking, analytics, and more over the internet.",
"Instead of buying and maintaining physical servers, you use AWS resources on demand, pay only for what you use, and scale anytime.",
"A growing e-commerce company gets high traffic during sales (e.g., Big Billion Days). They use AWS to quickly scale servers, handle millions of users, and reduce resources after the sale.",
"No physical hardware|Pay as you go|High availability|Global reach|Scalability|Focus on business, not infrastructure",
"Login to AWS Console|Go to EC2 service|Launch an EC2 instance|Choose Amazon Linux 2|Select instance type (t2.micro)|Configure security group (allow SSH)|Launch and connect using SSH",
"🔑 Console Login|🔲 EC2|🚀 Launch|💻 Connect",
"aws ec2 run-instances~--image-id ami-0abcdef1234567890~--instance-type t2.micro~--key-name my-key~--security-group-ids sg-12345678",
"Leaving resources running (unexpected charges)|Incorrect security group rules|Choosing wrong region|Not monitoring usage",
"S – Scale|P – Pay only for use|F – Focus on business",
"Cloud = Internet + On-demand Resources|AWS provides global infrastructure|Pay as you go|Use Console / CLI / SDK|Key services: EC2, S3, RDS, VPC, IAM");

L("1.2","Cloud Service Models","IaaS, PaaS and SaaS: who manages what.",
"Service models decide how much you manage. IaaS gives raw servers and networks, PaaS gives a ready platform to run code, SaaS gives a finished app.",
"IaaS = rent an empty kitchen. PaaS = rent a kitchen with tools, you only cook. SaaS = order food that is already made.",
"A startup runs its website on EC2 (IaaS), deploys its API on Elastic Beanstalk (PaaS), and uses Gmail and Slack (SaaS) for email and chat.",
"Choose the control level you need|Less admin work with PaaS and SaaS|Faster launch|Pay only for the layer you use",
"Open the EC2 console (IaaS example)|Open Elastic Beanstalk (PaaS example)|Compare what you must manage in each|Note that SaaS needs only a login",
"🧱 IaaS|🛠 PaaS|📱 SaaS",
"aws ec2 describe-instances^aws elasticbeanstalk describe-applications",
"Using IaaS when PaaS is enough|Forgetting you still patch the OS in IaaS|Confusing PaaS with SaaS",
"I = Infrastructure (you do most)|P = Platform (you bring code)|S = Software (you just use)",
"IaaS: EC2, VPC|PaaS: Elastic Beanstalk, RDS|SaaS: WorkMail, Chime|More control = more work");

L("1.3","Cloud Deployment Models","Public, private and hybrid cloud.",
"Deployment models describe where your resources live: public cloud (AWS), private cloud (your own data centre), or hybrid (both connected).",
"Public = rent a flat. Private = own house. Hybrid = own house plus a rented flat for extra guests.",
"A bank keeps customer records in its own data centre but runs its mobile app and analytics on AWS, connected by a private link.",
"Flexibility to choose where data lives|Helps meet rules for sensitive data|Burst to cloud when busy|Move to cloud step by step",
"Open the VPC console|Find Site-to-Site VPN connections|See where Direct Connect is listed|Read how on-premises connects to a VPC",
"🏢 On-premises|🔗 VPN / Direct Connect|☁ AWS VPC",
"aws configure list^aws ec2 describe-vpn-connections",
"Going hybrid without a clear reason|Ignoring network delay between sites|Skipping security on the link",
"Public = Rent|Private = Own|Hybrid = Both",
"Public: AWS|Private: your data centre or Outposts|Hybrid: VPN or Direct Connect|Pick by cost, rules and speed");

L("1.4","Global Infrastructure","Regions, Availability Zones and Edge Locations.",
"AWS is split into Regions (geographic areas), each with multiple Availability Zones (separate data centres). Edge locations cache content close to users.",
"Region = a city. AZ = separate buildings in that city. Edge location = a small local shop that stores popular items.",
"An Indian streaming app runs in Mumbai (ap-south-1) across 3 AZs and uses CloudFront edge locations so videos load fast everywhere.",
"Low delay for users|Survives a data centre failure|Meets data location rules|Easy to expand worldwide",
"Open the region dropdown in the console|Select Asia Pacific (Mumbai)|Open EC2 and view Availability Zones|Launch resources in two different AZs",
"🌍 Region|🏢 Availability Zone|📡 Edge Location",
"aws ec2 describe-regions --output table^aws ec2 describe-availability-zones --region ap-south-1",
"Choosing a far region (high delay)|Keeping everything in one AZ|Forgetting services differ by region",
"R = Region (area)|A = AZ (data centres)|E = Edge (cache)",
"A Region has 2 or more AZs (usually 3)|AZs are linked by fast networks|Edge locations power CloudFront|Mumbai = ap-south-1");

L("1.5","Shared Responsibility","Who secures what: AWS or you.",
"AWS secures the cloud itself (hardware, buildings, network). You secure what you put in the cloud (data, access, settings, OS patches on EC2).",
"AWS builds a strong building with locks. You decide who gets keys and what you keep inside.",
"A company stores customer files in S3. AWS protects the data centre. The company must keep the bucket private and use IAM rules.",
"Clear security ownership|Less hardware worry|Focus on data and access|Easier audits",
"Open the IAM console|Check users and their permissions|Open S3 and check Block Public Access|Review EC2 security groups",
"☁ AWS: security OF the cloud|👤 You: security IN the cloud",
"aws iam get-account-summary^aws s3api get-public-access-block --bucket my-bucket",
"Thinking AWS secures your data automatically|Public S3 buckets|Never patching EC2 instances",
"OF = AWS|IN = You",
"AWS: hardware, facilities, network|You: data, IAM, firewall rules|EC2 OS patching is yours|RDS patching is mostly AWS");

L("1.6","Benefits of Cloud","Why companies move to the cloud.",
"Cloud benefits: lower upfront cost, fast scaling, high availability, global reach, and faster experiments.",
"No big purchase. Rent what you need today, give it back tomorrow.",
"A school result website gets 100x traffic for one day. On AWS it scales up that day and costs very little the rest of the year.",
"Lower upfront cost|Scale up and down|Better uptime|Launch in minutes",
"Open the Billing console|View Free Tier usage|Set a budget alert (e.g. 5 USD)|Check Cost Explorer",
"💰 Low cost|📈 Scale|🌍 Global|⚡ Fast",
"aws budgets describe-budgets --account-id 123456789012",
"Not setting budget alerts|Leaving test resources running|Assuming cloud is always cheaper",
"C – Cost saving|A – Agility|G – Global reach",
"Big upfront spend becomes monthly spend|Elasticity = grow and shrink|Free Tier helps learning|Always set budgets");

L("2.1","Amazon EC2","Virtual servers in the cloud.",
"Amazon EC2 gives resizable virtual servers (instances). You pick the OS, CPU, memory and storage, and pay per second or hour.",
"A computer you rent by the hour. Stop it and compute billing stops.",
"A web shop runs its site on EC2, adds more instances before a sale, then stops them after.",
"Many instance types|Pay by use (On-Demand, Spot, Reserved)|Full OS control|Scales with Auto Scaling",
"Console > EC2 > Launch instance|Name it and pick the Amazon Linux AMI|Choose a Free Tier type (t2.micro or t3.micro)|Create a key pair and allow SSH in the security group|Launch and connect with SSH",
"🔑 Login|🔲 EC2|🚀 Launch|💻 Connect",
"aws ec2 start-instances --instance-ids i-0abc123^aws ec2 stop-instances --instance-ids i-0abc123^aws ec2 terminate-instances --instance-ids i-0abc123",
"Leaving instances running|Opening SSH to 0.0.0.0/0|Losing the key pair|Confusing Stop with Terminate",
"Stop = Pause|Terminate = Delete forever|Always check the bill",
"AMI = OS template|Instance type = size|Key pair = SSH login|Security group = firewall");

L("2.2","Auto Scaling & Load Balancing","Add servers when busy, share traffic fairly.",
"Auto Scaling adds or removes EC2 instances based on demand. An Elastic Load Balancer spreads traffic across them.",
"More customers, open more counters. Fewer customers, close some. A manager at the door sends each person to a free counter.",
"A ticket-booking site doubles its servers when sales open and the load balancer shares users equally.",
"Handles traffic spikes|Saves cost at low traffic|Replaces failed servers|High availability across AZs",
"Create a Launch Template|Create a Target Group|Create an Application Load Balancer|Create an Auto Scaling Group with the template|Set a CPU target (e.g. 50%)",
"👥 Users|⚖ Load Balancer|🔲 EC2 Group",
"aws autoscaling create-auto-scaling-group~--auto-scaling-group-name web-asg~--launch-template LaunchTemplateName=web-lt~--min-size 1 --max-size 4~--vpc-zone-identifier subnet-111,subnet-222",
"Wrong min and max values|No health checks|Only one AZ|Forgetting to delete the load balancer (it costs money)",
"Auto Scaling = Count|ELB = Traffic|Use both together",
"ALB = HTTP/HTTPS|NLB = very fast TCP|Min / Desired / Max sizes|Spread across 2+ AZs");

L("3.1","Amazon S3","Object storage for any file.",
"Amazon S3 is object storage. You store files (objects) in buckets and get very high durability (99.999999999%).",
"A huge online locker where each file has its own link and you pay only for the space used.",
"A news site keeps all images and videos in S3 and serves them through CloudFront.",
"Practically unlimited storage|11 nines durability|Cheap storage classes|Static website hosting",
"Console > S3 > Create bucket|Pick a unique name and region|Keep Block Public Access ON|Upload a file|Open it with a presigned URL",
"📁 Bucket|📄 Object|🔐 Permissions",
"aws s3 mb s3://my-unique-bucket-123^aws s3 cp notes.txt s3://my-unique-bucket-123/^aws s3 ls s3://my-unique-bucket-123",
"Making buckets public by mistake|Bucket name already taken|No lifecycle rules (cost grows)|Using S3 like a disk for databases",
"Bucket = Box|Object = File|Never public by default",
"Object storage, not block|Max object size 5 TB|Classes: Standard, IA, Glacier|Versioning protects deletes");

L("3.2","Amazon EBS","Disks for your EC2 servers.",
"Amazon EBS gives block storage volumes that attach to an EC2 instance, like a hard disk.",
"A pen drive you plug into your rented computer. It keeps data even if the computer stops.",
"A database server on EC2 keeps its data on an EBS gp3 volume and takes daily snapshots.",
"Persistent disk|Snapshots for backup|Resize without rebuilding|SSD and HDD types",
"EC2 > Volumes > Create volume|Choose gp3, 8 GiB, same AZ as the instance|Attach it to the instance|Format and mount it in Linux|Create a snapshot",
"💽 Volume|🔌 Attach|🔲 EC2|📸 Snapshot",
"aws ec2 create-volume --size 8 --volume-type gp3 --availability-zone ap-south-1a^aws ec2 create-snapshot --volume-id vol-0abc123",
"Volume in a different AZ than EC2|Forgetting unused volumes (still billed)|No snapshots|Not mounting the disk",
"EBS = Disk|S3 = Locker|EFS = Shared folder",
"Must be in same AZ as the instance|gp3 = default SSD|Snapshots are stored in S3|Check Delete on termination");

L("4.1","Amazon VPC","Your private network in AWS.",
"A VPC is your private network in AWS. You control IP ranges, subnets, route tables, gateways and firewalls.",
"Your own fenced plot inside AWS. You decide the gates, roads and who can enter.",
"A company puts its web servers in a public subnet and its database in a private subnet with no direct internet access.",
"Network isolation|Full control of IP ranges|Public and private subnets|Layered security",
"VPC > Create VPC (VPC and more)|Use CIDR 10.0.0.0/16|Create public and private subnets|Attach an Internet Gateway|Add a route to it in the public route table",
"🌐 Internet|🚪 Internet Gateway|🧭 Route Table|🧩 Subnet",
"aws ec2 create-vpc --cidr-block 10.0.0.0/16^aws ec2 create-subnet --vpc-id vpc-0abc123 --cidr-block 10.0.1.0/24",
"Overlapping CIDR ranges|Databases in public subnets|Missing route to the internet gateway|Mixing up Security Group and NACL",
"Public subnet = Route to IGW|Private subnet = No direct route|SG = Instance firewall",
"VPC is regional, subnet is per AZ|IGW = internet door|NAT = outbound for private|SG is stateful, NACL is stateless");

L("5.1","Amazon RDS","Managed relational databases.",
"Amazon RDS runs managed relational databases (MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, Aurora). AWS handles backups, patching and failover.",
"A database where AWS does the boring admin work, so you focus on tables and queries.",
"An online store runs PostgreSQL on RDS with Multi-AZ so orders keep working even if one data centre fails.",
"Automatic backups|Multi-AZ failover|Read replicas for speed|Easy patching",
"RDS > Create database|Pick MySQL or PostgreSQL|Choose the Free tier template|Set username and password|Allow the DB port only from your app's security group",
"💻 App|🛢 RDS|🔁 Standby / Replica",
"aws rds create-db-instance~--db-instance-identifier mydb~--engine postgres~--db-instance-class db.t3.micro~--allocated-storage 20~--master-username admin --master-user-password <password>",
"Making the database public|Weak master password|Low backup retention|Leaving it running when idle",
"RDS = SQL tables|Multi-AZ = Safety|Read replica = Speed",
"Relational (SQL) engines|Multi-AZ for high availability|Read replicas for scale|Aurora is AWS's own engine");

L("5.2","Amazon DynamoDB","Serverless NoSQL database.",
"DynamoDB is a serverless NoSQL key-value and document database with single-digit millisecond speed at any scale.",
"A super-fast digital notebook where you look things up by a key, and it never runs out of pages.",
"A game app stores player scores in DynamoDB and reads them in milliseconds for millions of players.",
"No servers to manage|Very fast at any scale|Pay per request option|Global tables",
"DynamoDB > Create table|Set a partition key (e.g. userId)|Choose On-demand capacity|Add items with Create item|Query by key",
"🔑 Key|📄 Item|🗂 Table",
"aws dynamodb create-table~--table-name Players~--attribute-definitions AttributeName=userId,AttributeType=S~--key-schema AttributeName=userId,KeyType=HASH~--billing-mode PAY_PER_REQUEST",
"Choosing a bad partition key|Using Scan on big tables|Treating it like SQL with joins|Over-provisioning capacity",
"Key = Find fast|No joins|Design by access pattern",
"NoSQL key-value|Partition key + optional sort key|On-demand or provisioned|Use Query, not Scan");

L("6.1","AWS IAM","Who can do what in your account.",
"IAM controls who can do what in your AWS account using users, groups, roles and policies.",
"The security desk of your account: it checks who you are and what you are allowed to touch.",
"A team gives developers read-only S3 access and gives an EC2 server a role to write logs, with no hard-coded keys.",
"Fine-grained permissions|No shared passwords|Roles for services|Free to use",
"IAM > Users > Create user|Add the user to a group with a policy|Enable MFA|Create a role for EC2 with S3 read access|Do not use root for daily work",
"👤 User|👥 Group|📜 Policy|🎭 Role",
"aws iam create-user --user-name dev1^aws iam attach-user-policy --user-name dev1 --policy-arn arn:aws:iam::aws:policy/ReadOnlyAccess",
"Using the root account|Giving AdministratorAccess to everyone|Hard-coding access keys in code|No MFA",
"Least privilege = Only what is needed|Roles over keys",
"User = person|Role = temporary identity|Policy = JSON permissions|Always enable MFA");

L("8.1","Amazon CloudWatch","Metrics, logs and alarms.",
"CloudWatch collects metrics, logs and alarms from AWS services and your apps so you can watch health and react.",
"A dashboard and alarm system for your servers. It tells you when CPU is high or something breaks.",
"A company gets an email alert when the CPU of its web servers stays above 80% for 5 minutes.",
"One place for metrics and logs|Alarms with notifications|Dashboards|Can trigger Auto Scaling",
"CloudWatch > Alarms > Create alarm|Select the EC2 CPUUtilization metric|Set threshold 80%|Send to an SNS email topic|Confirm the email subscription",
"📊 Metric|🔔 Alarm|📧 SNS|⚙ Action",
"aws cloudwatch describe-alarms^aws logs tail /aws/lambda/my-fn --follow",
"No alarms at all|Logs kept forever (cost)|Alerting on too many things|Forgetting the SNS confirmation",
"Metric = Number|Log = Text|Alarm = Alert",
"Basic metrics every 5 min|Logs live in log groups|Alarm states: OK, ALARM|Pair with SNS");

L("10.1","AWS Lambda","Run code without servers.",
"AWS Lambda runs your code without servers. You upload a function, AWS runs it on events, and you pay only for run time.",
"Write a small function and AWS runs it when something happens. No server to manage.",
"When a photo is uploaded to S3, a Lambda function creates a thumbnail automatically.",
"No server management|Pay per request and time|Scales automatically|Many triggers",
"Lambda > Create function|Choose Python, Author from scratch|Paste your code|Add a trigger (S3 or API Gateway)|Click Test",
"⚡ Event|λ Lambda|📤 Result",
"aws lambda invoke --function-name my-fn out.json^aws lambda list-functions",
"Timeout too short|Too little memory|Huge packages|Missing IAM role permissions",
"Event in > Code runs > Pay little",
"Max run time 15 minutes|Memory 128 MB to 10 GB|Triggers: S3, API Gateway, SQS|Billed per millisecond");
